version: "3"
services:
  startersaas-go-api:
    container_name: startersaas-go-api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/go/src/app/
      - ./go.mod:/go/src/app/go.mod
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    networks:
      - startersaas-network
    depends_on:
      - startersaas-redis
      - startersaas-mongo

  startersaas-redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    volumes:
      - redis:/data
    networks:
      - startersaas-network

  startersaas-mongo:
    image: mongo:7.0
    volumes:
      - mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    networks:
      - startersaas-network

  startersaas-mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "${MAILHOG_UI_PORT}:8025" # web ui
    env_file:
      - .env
    networks:
      - startersaas-network

volumes:
  redis:
  mongo:

networks:
  startersaas-network:
    external: true
